# Generated by Django 3.1.3 on 2020-11-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, null=True, verbose_name='Código')),
                ('quantidadeEmEstoque', models.PositiveIntegerField(null=True, verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, null=True, verbose_name='Código')),
                ('valorParcela', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, null=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=144, null=True, verbose_name='Descrição do produto')),
                ('imagem', models.ImageField(default=None, null=True, upload_to='produtos/static/imgs')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('marca', models.CharField(max_length=40, null=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produto')),
                ('modelo', models.CharField(max_length=60, null=True, verbose_name='Modelo')),
            ],
            bases=('produtos.produto',),
        ),
    ]
