# Generated by Django 3.1.3 on 2020-12-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20201204_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicicleta',
            options={'verbose_name': 'Bicicleta', 'verbose_name_plural': 'Bicicletas'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
