# Generated by Django 3.1.3 on 2020-12-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=60, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(max_length=50, null=True, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=30, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, null=True, verbose_name='Estado')),
                ('pais', models.CharField(max_length=30, null=True, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cel', 'celular'), ('res', 'residencial'), ('com', 'comercial')], max_length=3, null=True, verbose_name='Tipo do telefone')),
                ('numero', models.CharField(max_length=12, null=True, verbose_name='Número')),
            ],
        ),
    ]
