# Generated by Django 3.1.3 on 2020-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, verbose_name='Código')),
                ('quantidadeEmEstoque', models.PositiveIntegerField(verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, verbose_name='Código')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=12, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('cel', 'celular'), ('res', 'residencial'), ('com', 'comercial')], max_length=3, verbose_name='Tipo do telefone'),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
