# Generated by Django 3.1.3 on 2020-11-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20201120_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='parcelamento',
        ),
    ]
