# Generated by Django 3.1.3 on 2020-11-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_remove_produto_parcelamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='produto_ptr',
        ),
        migrations.DeleteModel(
            name='ItemInventario',
        ),
        migrations.DeleteModel(
            name='Parcelamento',
        ),
        migrations.DeleteModel(
            name='Bicicleta',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
