# Generated by Django 3.1.3 on 2020-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20201122_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
