# Generated by Django 3.1.3 on 2020-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_delete_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerente',
            options={'verbose_name': 'Gerente', 'verbose_name_plural': 'Gerentes'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='E-mail'),
        ),
    ]
