# Generated by Django 3.1.3 on 2020-12-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_auto_20201204_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminventario',
            options={'verbose_name': 'Item do inventário', 'verbose_name_plural': 'Itens do inventário'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'ordering': ['data_adicionado'], 'verbose_name': 'Item do pedido', 'verbose_name_plural': 'Itens do pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['data_do_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
