# Generated by Django 3.1.3 on 2020-11-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0002_auto_20201110_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome: ')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.endereco')),
                ('telefone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.telefone')),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
    ]
