# Generated by Django 3.1.3 on 2020-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='nome',
            field=models.CharField(max_length=40, null=True, verbose_name='Nome'),
        ),
    ]
