# Generated by Django 3.1.3 on 2020-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201119_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='E-mail'),
        ),
    ]
